name: Test Unity Activation
run-name: ${{ github.actor }} is testing unity activation 🚀
on:
  workflow_dispatch: {}
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  testActivation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
